### ISSUE TITLE
the <?php and ?>

### ISSUE THREAD

**Issue by KnuTNatioN** [Alchiadus/base16-syntax#25]
Thanks for your work, but since the last Update (28.01.2017) the tags:
<?php
and 
?>   
are brown... it WAS yellow... how i change it back?
I do not know if this issue is a Problem of base16-syntax or the seti-ui.

MY Atom:
UI Theme = Seti (Orange)
Syntax Theme: Base16 (Sheme: Seti | Style: Dark)
and my own style.less:

atom-text-editor {
   background-color: #0d0011;
}
atom-text-editor::shadow .gutter {
    background-color: #0d0011;
}
atom-text-editor::shadow .lines .line.cursor-line {
  background-color: #120017;
}
Thank you in advance.

**Comment by Alchiadus** [comment]
I am not sure what caused the change, but if you'd like to use the yellow color from the Seti scheme try adding the following snippet to your stylesheet:

```less
// Customize syntax highlighting of `<?php` and `?>` tags.
atom-text-editor::shadow .punctuation.section.embedded.begin.php, // Remove me, I'm deprecated!
atom-text-editor::shadow .punctuation.section.embedded.end.php, // Remove me, I'm deprecated!
atom-text-editor .syntax--punctuation.syntax--section.syntax--embedded.syntax--begin.syntax--php,
atom-text-editor .syntax--punctuation.syntax--section.syntax--embedded.syntax--end.syntax--php, {
  color: #FFCC66;
}
```

*Note: Atom has [deprecated the use of Shadow DOM](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html) and removed it in [Atom 1.13](http://blog.atom.io/2017/01/10/atom-1-13.html), so I recommend removing the two corresponding lines from my snippet, I only added them for completeness. Consider updating your stylesheet's existing shadow-piercing selectors by prepending each class with `.syntax--` instead (and removing `::shadow`) so your custom styling won't break in the future.*

If you'd like to apply styling to (other) syntax elements, you can find their selectors as follows:
1. Place your cursor on the desired element in the editor.
2. Open the Command Palette and enter `Editor: Log Cursor Scope`.

In the example above, you'll get:
```
Scopes at Cursor

- text.html.php
- meta.embedded.line.php
- punctuation.section.embedded.begin.php
```

Hopefully that helps!
